# Generated by Django 4.1.7 on 2023-04-10 23:45

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('read_counter', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': '__Разделы',
                'ordering': ('title',),
                'default_related_name': 'sections',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('read_counter', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'подраздел',
                'verbose_name_plural': '_Подразделы',
                'ordering': ('title',),
                'default_related_name': 'subsections',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('read_counter', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(blank=True, null=True, upload_to=materials.models.article_directory_path, verbose_name='Файл работы')),
                ('content', models.TextField(blank=True, null=True, verbose_name='LanTeX / MathML')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Сконвертировано')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.section', verbose_name='Раздел')),
                ('subsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.subsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
