# Generated by Django 4.1.7 on 2023-04-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.section', verbose_name='Раздел'),
        ),
    ]
