# Generated by Django 4.1.7 on 2023-04-14 21:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_section_options_alter_subsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_counter',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subsection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='section', chained_model_field='section', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='materials.subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='section',
            name='read_counter',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='read_counter',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
