# Generated by Django 4.1.7 on 2023-04-23 20:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_article_read_counter_alter_article_subsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='section',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subsection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='section', chained_model_field='section', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='materials.subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
