# Generated by Django 4.1.7 on 2023-06-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_contactmodel_remove_section_author_section_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
    ]
